-- Seed songs table with Stellar Fingers song
INSERT INTO songs (
  title,
  composer,
  artist,
  genre,
  tempo,
  key_signature,
  time_signature,
  duration_seconds,
  beginner_midi_path,
  intermediate_midi_path,
  advanced_midi_path,
  beginner_sheet_music_path,
  intermediate_sheet_music_path,
  advanced_sheet_music_path,
  backing_track_path,
  is_public_domain,
  is_active,
  order_index,
  created_at,
  updated_at
) VALUES (
  'Stellar Fingers',
  'Traditional',
  NULL,
  'folk',
  120,
  'C major',
  '4/4',
  120,
  'stellar-fingers/beginner.mid',
  'stellar-fingers/intermediate.mid',
  'stellar-fingers/advanced.mid',
  'stellar-fingers/beginner.xml',
  'stellar-fingers/intermediate.xml',
  'stellar-fingers/advanced.xml',
  'stellar-fingers/backing-track.mp3',
  true,
  true,
  1,
  NOW(),
  NOW()
) ON CONFLICT (title) DO NOTHING;
